namespace :dev do
  desc 'Populate the database with collections of books.'
  task :populate => :environment do
    25.times do |i|
      Category.first.products.create(title: 'Rails 4 in Action1 ' + i.to_s, description: 'Design and develop your very own responsive web applications using Java, jQuery, and AJAX Overview A practical guide to empower you to develop responsive web applications by combining the strengths of AJAX and jQuery Learn how to build a series of web applications on top of a website quickly and efficiently By the end of this book, you will have mastered ways with which you can leverage AJAX and jQuery as per your project needs In Detail AJAX is a web development technique that allows a web page to be updated with new information without having to reload the page. jQuery is a JavaScript library that harnesses AJAX interactions to allow rapid web development. Together, they are a powerful combination, and are generally considered by frontend web developers as technologies that complement each other perfectly. Developing Responsive Web Applications with AJAX and jQuery will empower you with the skills required to create responsive web applications in a quick and efficient manner. The book begins by identifying the key benefits of a responsive application for a commercial site, and then covers how to develop a layout using Bootstrap 3 and adding dynamic visuals to your web application using AJAX calls. By the end of this book, you will be able to develop responsive web applications by combining AJAX development techniques with the jQuery JavaScript library.', image_url: 'SP1.jpg', price: i)
      Category.second.products.create(title: 'Developing Responsive Web Applications with AJAX and jQuery1 ' + i.to_s, description: 'Design and develop your very own responsive web applications using Java, jQuery, and AJAX Overview A practical guide to empower you to develop responsive web applications by combining the strengths of AJAX and jQuery Learn how to build a series of web applications on top of a website quickly and efficiently By the end of this book, you will have mastered ways with which you can leverage AJAX and jQuery as per your project needs In Detail AJAX is a web development technique that allows a web page to be updated with new information without having to reload the page. jQuery is a JavaScript library that harnesses AJAX interactions to allow rapid web development. Together, they are a powerful combination, and are generally considered by frontend web developers as technologies that complement each other perfectly. Developing Responsive Web Applications with AJAX and jQuery will empower you with the skills required to create responsive web applications in a quick and efficient manner. The book begins by identifying the key benefits of a responsive application for a commercial site, and then covers how to develop a layout using Bootstrap 3 and adding dynamic visuals to your web application using AJAX calls. By the end of this book, you will be able to develop responsive web applications by combining AJAX development techniques with the jQuery JavaScript library.', image_url: 'SP2.jpg', price: i)
      Category.third.products.create(title: 'Practical Node.js: Building Real-World Scalable Web Apps1 ' + i.to_s, description: 'Design and develop your very own responsive web applications using Java, jQuery, and AJAX Overview A practical guide to empower you to develop responsive web applications by combining the strengths of AJAX and jQuery Learn how to build a series of web applications on top of a website quickly and efficiently By the end of this book, you will have mastered ways with which you can leverage AJAX and jQuery as per your project needs In Detail AJAX is a web development technique that allows a web page to be updated with new information without having to reload the page. jQuery is a JavaScript library that harnesses AJAX interactions to allow rapid web development. Together, they are a powerful combination, and are generally considered by frontend web developers as technologies that complement each other perfectly. Developing Responsive Web Applications with AJAX and jQuery will empower you with the skills required to create responsive web applications in a quick and efficient manner. The book begins by identifying the key benefits of a responsive application for a commercial site, and then covers how to develop a layout using Bootstrap 3 and adding dynamic visuals to your web application using AJAX calls. By the end of this book, you will be able to develop responsive web applications by combining AJAX development techniques with the jQuery JavaScript library.', image_url: 'SP3.jpg', price: i)
    end
  end
end


